name: Test Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Hello World from Job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: echo "Hello World from Job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: echo "Hello World from Job 3"

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate random success/failure
        run: |
          echo "Running Job 4..."
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Job 4 succeeded!"
          else
            echo "Job 4 failed randomly!"
            exit 1
          fi

  job5_wait:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3, job4]
    steps:
      - name: Waiting for manual release
        env:
          GH_TOKEN: ${{ secrets.POLLING_TOKEN }}
          REPO: ${{ github.repository }}
          FILE_PATH: "release_trigger.txt"
        run: |
          echo "Job 5 is now waiting for release_trigger.txt..."
          while true; do
            status_code=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$REPO/contents/$FILE_PATH)
            if [ "$status_code" -eq 200 ]; then
              echo "Release_trigger.txt detected! Proceeding with Job 5.."
              break
            fi
            echo "Still waiting for API Trigger..."
            sleep 10
          done
