name: Test Workflow
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Hello World from Job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: echo "Hello World from Job 2"
        
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: echo "Hello World from Job 3"
        
  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Job 4
        run: echo "Hello World from Job 4"
        
  job5_wait:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3, job4]
    steps:
      - name: Waiting for manual release
        run: |
          echo "Job 5 is waiting..."
          while [ ! -f "$GITHUB_WORKSPACE/release_trigger.txt" ]; do
            sleep 5
            echo "Still waiting..."

          done

          echo "Release detected. Proceeding.."
